### ISSUE TITLE
Rustfix doesn't work in the presence of multiple targets

### ISSUE THREAD

**Issue by oli-obk** [killercup/rustfix#22]
I get

```
SubcommandError("cargo rustc", "error: extra arguments to `rustc` can only be passed to one target, consider filtering\nthe package by passing e.g. `--lib` or `--bin NAME` to specify a single target\n")
```

Should probably use `cargo_metadata` to find all targets like `cargo clippy` does

**Comment by oli-obk** [comment]
since `rustfix --clippy` forwards to `cargo clippy` you get all of this for free... so maybe this point is moot?

**Comment by killercup** [comment]
Do you think it'd be a good idea to always use/require clippy?

**Comment by oli-obk** [comment]
I do, but ppl might complain. But they can use `--allow=clippy` to disable just the clippy linting.

**Comment by oli-obk** [comment]
Idea: we always require clippy to be installed (it'll be available through rustup in the near future anyway), but when `--clippy` is passed, only then are clippy's lints actually warned against

**Comment by oli-obk** [comment]
This works now. `--clippy` has been changed to enable the clippy lints, but `cargo clippy` is unconditionally used
