### ISSUE TITLE
Continuous integration

### ISSUE THREAD

**Issue by oli-obk** [killercup/rustfix#24]
Not sure how that would look... probably create some mode that automatically applies suggestions and then compare the file out put and command line output.

Or maybe we can feed a file as command line input.

**Comment by killercup** [comment]
Hm, CI can just run clippy and if it fails the user can run rustfix themselves.

But vastly more amazing would be to have a CI script that creates a Github review that comments on the lines where lint warnings occurred and where you can reply "fix" to trigger a bot that applies the suggestion!

**Comment by oli-obk** [comment]
I meant for testing rustfix. But good idea!

**Comment by killercup** [comment]
Haha, okay, that's good as well. I think there was a readline crate that has a good test mode, but I don't recall if rustfix is using that one 😅

**Comment by llogiq** [comment]
I'd be careful trying stuff like this – you may very well run into endless loops with that. And a --batchmode could be useful, too. In conjunction with the "optimization fuel" idea from the recent struct reordering PR one could even automate finding fixes that don't work, sort of like a crater for rustfix.

**Comment by oli-obk** [comment]
we're now simply feeding a file with command line input to rustfix and test whether the output + changes applied match the expected ones (similar to ui tests)
