### ISSUE TITLE
Deal with multiple replacements in one file

### ISSUE THREAD

**Issue by killercup** [killercup/rustfix#3]
Currently, rustfix will explode (or wreck your source file to be more precise) when it applies multiply suggestions to the same file -- The file changes but we still use the original byte offsets given by rustc.

We could instead use a rope-like data structure and remember the original indices. Also, it might be nice to only write the file once, after all suggestions for a file were dealt with by the user (i.e., ≥ 0 were accepted).

**Comment by killercup** [comment]
I'm no expert on ropes – but I may have another idea. Please tell me if this is something that already exists (even better if there is a crate as well!)

I'm imagining storing this in a map of `Range`s of line numbers mapped to `Cow`'s (exercise for the reader: Make a joke with 'field of cows').

Reading the file, you begin with a map with one node that maps `start...end` (first to last byte in the file) to a Cow that borrows the whole slide of the input data. When you want to change some byte range `x..y`, you replace that one node with three: The first maps `0..x` to a Cow that borrows `0..x`, the second one maps `x...y` to a Cow that owns the new content, and the third one maps `y+1...end` to the Cow that borrows the `y+1...end`.

The important bit is this – you can replace the `x...y` slice with a new slice that is _not_ of length `y-x`.

As we are unlikely to do many replacements per file (≥100 seems unlikely in practice, so we are probably dealing with ≤100 ranges to look at), a simple `VecMap<Range<usize>, Cow<'input, str>>` could suffice for this (instead of a tree we need to balance). Additionally, we might even be able to keep track of a cursor and never even need to scan through all the previous ranges while inserting at all – we are almost certainly only adding/splitting ranges with increasing byte offsets.(Lints go linearly through the file, or we can collect all changes to apply per file, sort them and do them at once.)

**Comment by killercup** [comment]
@eddyb mentioned I should look at [xi-rope](https://github.com/google/xi-editor/blob/master/rust/rope/), and adjust it to not track index updates. (This might also be interesting to xi-rope upstream if it has similar use cases.)

**Comment by mcarton** [comment]
You could just load the file in a `String` and replace the suggestions from the last to the first, that way the byte offsets given by rustc stay valid all along and you don't need anything as fancy as ropes.

**Comment by killercup** [comment]
That is actually brilliant :O

**Comment by killercup** [comment]
Using a trivial `suggestions.rev()` version right now.
