### ISSUE TITLE
Rename binary to cargo-fix

### ISSUE THREAD

**Issue by oli-obk** [killercup/rustfix#32]
After a `cargo install rustfix`, the subcommand `cargo fix` would be available.

**Comment by killercup** [comment]
Can we cheat and add two `[[bin]]` with "rustfix" and "cargo-fix" as names, but both with `src/main.rs` as target? :D

**Comment by oli-obk** [comment]
Cargo will produce

```
warning: file found to be present in multiple build targets: src/main.rs
```

if we do that :(

I guess we can move the logic to lib.rs and load it from both `src/bin/rustfix.rs` and `src/bin/cargo-fix.rs` which simply have the same source code. Or go the extremely hacky route of creating `src/bin/cargo-fix.rs` with the content `include!("../main.rs")`
