### ISSUE TITLE
How to force rustfix to rerun

### ISSUE THREAD

**Issue by rohitjoshi** [killercup/rustfix#34]
i am using VSCode configured to run `cargo clippy` on save which shows me lot of warning particularly unused imports. If I run `rustfix`,  I get `I don't have any suggestions for you right now. Check back later!`.  

How can I force rustfix to run and fix suggestion provided by clippy?  I even tried to delete the target directory but always get the same message.

**Comment by oli-obk** [comment]
This is probably because running rustfix will not stop the compilation. We probably just need to pass a -Zno-trans or whatever that flag was called.

**Comment by killercup** [comment]
Yeah, that's a known issue.

I have no idea how to tell cargo to always consider the files changed (so
it recompiles) *except* for writing a build.rs script that emits some magic
strings to stdout (cargo-rerun-if-changed:src or something like that) or by
actually executing `touch src/lib.rs`. Sadly, both are not easy to do in a
way that works for all projects.

In the meantime you can of course manually change a source file (just
saving a file should suffice), or run `cargo clean` (which recompiles
everything).

Rohit Joshi <notifications@github.com> schrieb am Mi. 24. Mai 2017 um 05:16:

**Comment by rohitjoshi** [comment]
@killercup `cargo clean; rustfix --clippy` doesn't work either.

```
cargo clean; rustfix --clippy
I don't have any suggestions for you right now. Check back later!
```

I tried deleting few empty spaces from main.rs or adding comment does not help either but when VSCode runs `cargo clippy`, I see large number of suggestions/warnings.

**Comment by oli-obk** [comment]
I've seen that before... can you run cargo clippy manually in the directory where you run rustfix?

**Comment by rohitjoshi** [comment]
```
cargo clean; rustfix --clippy
I don't have any suggestions for you right now. Check back later!
```

```
$ cargo clippy
error: no such subcommand: `clippy`

$ cargo --clippy
error: Unknown flag: '--clippy'

Usage:
    cargo <command> [<args>...]
    cargo [options]
```

**Comment by oli-obk** [comment]
ah, that's the root of the problem. You need to have clippy installed

`cargo install clippy` should do the trick on today's nightly

**Comment by rohitjoshi** [comment]
I installed `clippy` and updated `rustfix` from the master.  It works now. 👍 
I really like `rustfix` and should be part of the `cargo` tooling/VSCode plugin. See my [comment](https://www.reddit.com/r/programming/comments/7ty23x/rust_2018_roadmap/dtgr6eb/)

**Comment by killercup** [comment]
Glad to hear it, @rohitjoshi! vscode-rls can actually apply the same suggestions, it just doesn't have clippy right now :)
