### ISSUE TITLE
Stabilize test output across clippy versions

### ISSUE THREAD

**Issue by killercup** [killercup/rustfix#45]
[Travis failed](https://travis-ci.org/killercup/rustfix/jobs/329422200#L681) because the link to the clippy docs is no longer `…/v0.0.177/…` but `…/v0.0.180/…`. This is not a useful failure.

**Comment by oli-obk** [comment]
We just need to `set_var("CLIPPY_DISABLE_DOCS_LINKS", "true");`

**Comment by noofh-22** [comment]
i

**Comment by noofh-22** [comment]
hi
